apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mynapp-sts
spec:
  selector:
    matchLabels:
      app: mynapp-sts
  serviceName: mynapp-svc-sts
  replicas: 2
  template:
    metadata:
      labels:
        app: mynapp-sts
    spec:
      containers:
      - name: mynapp
        image: c1t1d0s7/myweb:v1
        ports:
        - containerPort: 8080
